### ISSUE TITLE
Size of board?

### ISSUE THREAD

**Issue by Tall-Paul** [uzsito/attach-hexa#1]
Hi, could you update the readme to include the size of the board (width * height)?  PCBWAY asks for this when requesting a PCB.

Cheers

**Comment by uzsito** [comment]
> Hi, could you update the readme to include the size of the board (width * height)? PCBWAY asks for this when requesting a PCB.
> 
> Cheers

Hello,

Of course, no problem. It is 91 mm* 26 mm according to my former PCBWAY orders (measured by their system).

From KiCAD, it seems it's 91,338 mm * 25,87 mm.

Readme updated.
